//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 03:22:57 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://ro.wikipedia.org/wiki/World_Wide_Web", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.ro_wikipedia_org.wiki.world_wide_web;
